[package]
name = "binance-arbitrage-engine"
version = "0.1.0"
authors = ["David Holtz <david.richard.holtz@gmail.com>"]
edition = "2018"

[dependencies]
binance = "0.5.0"
zmq = "0.9"
bytevec = "0.2.0"
